##
##  Makefile -- Build procedure for sample mvproc Apache module
##  Autogenerated via ``apxs -n mvproc -g''.
##

APACHE_HOME=/usr/share/apache2

builddir=.
top_srcdir=$(APACHE_HOME)
top_builddir=$(APACHE_HOME)
include $(APACHE_HOME)/build/special.mk

#   the used tools
APXS=/usr/bin/apxs2
APACHECTL=/usr/sbin/apachectl

#   additional defines, includes and libraries
#DEFS=
INCLUDES=-I/usr/include/apreq2
LIBS=-lmysqlclient_r -lapreq2
LDFLAGS=-Wl,--as-needed -Wl,-z,relro $(LIBS)

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_mvproc.o mod_mvproc.lo mod_mvproc.slo mod_mvproc.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/mvproc

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

